theme = "solarized-dark"
icons = "material-nf"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "net"
device = "wlan0"
format = "{signal_strength}"
interval = 1

[[block]]
block = "sound"
driver = "pulseaudio"
format = "{volume}"
max_vol = 100

[[block]]
block = "music"
buttons = [ "prev", "play", "next" ]

[[block]]
block = "pacman"
interval = 600
format = "{pacman}"

[[block]]
block = "battery"
interval = 5
format = "{percentage} {time}"

[[block]]
block = "time"
interval = 1
format = "%Y %b %d %R"
